### ISSUE TITLE
Cannot find Client constructor

### ISSUE THREAD

**Issue by egorzaremba** [JsCommunity/jsonrpc-websocket-client#40]
```
const Client = require('jsonrpc-websocket-client')
 
async function main () {
  const client = new Client('ws://example.org')
 
  console.log(client.status)
}
```
"jsonrpc-websocket-client": "^0.4.1"
```
TypeError: Client is not a constructor
    at main (/app/infuratest.js:28:18)
    at Object.<anonymous> (/app/infuratest.js:46:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
```

**Comment by julien-f** [comment]
The default export is the `default` property (for ES2015 module compat):

```js
const Client = require('jsonrpc-websocket-client').default
```
